---
- name: "Checking to see if httpd is installed prior to us installing it"
  stat:
    path: "/usr/lib/systemd/system/httpd.service"
  register: wassvchttpd

- name: Software packages are present
  yum:
    name:
      - nano
      - unzip
      - python3-PyMySQL
      - mariadb
      - policycoreutils-python
      - httpd
      - php
      - php-mysql
    state: latest
  ignore_errors: true

