---
- name: "checking to see if firewalld is running"
  shell: 'pgrep firewalld | wc -l'
  register: isfirewalldon
  changed_when: no

- name: enabling firewall rules
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - http
    - https
  ignore_errors: yes
  when:  isfirewalldon.stdout > "0"

