---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
  - name: Use a single pattern that contains a comma formatted as a list
    raw: ls -1 ./varfiles/app_*yml
    register: filenames

  - name: debug filenames
    debug: 
      msg: "filenames are {{ filenames }}"

  - name: debug one filename
    debug: 
      msg: "filenames.stdout_lines[0] is {{ filenames.stdout_lines[0] }}"
    with_items: "{{ filenames.stdout_lines }}"

