- name: CatMeme INSTALL
  tower_job_template:
    name: "Wordpress LAMP Kitty Cat Site - Install"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "F5 Lab Demo"
    playbook: "LocalProjects/CatMemeLAMP/wordpress_install.yml"
    limit: web
    credential: Ansible User
    state: "present"

- name: CatMeme RESET
  tower_job_template:
    name: "Wordpress LAMP Kitty Cat Site - Reset"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "F5 Lab Demo"
    playbook: "LocalProjects/CatMemeLAMP/wordpress_reset.yml"
    limit: web
    credential: Ansible User
    state: "present"

