- name: Create tower job template
  tower_job_template:
    name: "Install Wordpress LAMP Kitty Cat Site"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "F5 Lab Demo"
    playbook: "LocalProjects/CatMemeLAMP/wordpress_install.yml"
    credential: Ansible User
    state: "present"

