- name: Create tower job template
  tower_job_template:
    name: "Manage F5 Apps"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "F5 Lab Demo"
    playbook: "LocalProjects/F5Projects/01_ManageApps/apps-from-config-files.yml"
    credential: Ansible User
    state: "present"

