---
- name: Insert the root machine credential
  uri:
    url: https://localhost/api/v2/credentials/
    validate_certs: no
    method: POST
    user: "admin"
    password: "{{ ansible_password }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |
      {
          "name": "Ansible User",
          "description": "Non-privileged lab user account",
          "organization": 1,
          "credential_type": 1,
          "inputs": {
              "username": "{{ ansible_user }}",
              "password": "{{ ansible_password }}"
          }
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False
  tags:
  - credential
  - add_stuff

- name: Get the new credential ID
  uri:
    url: https://localhost/api/v2/credentials/?name=Ansible%20User
    validate_certs: no
    method: GET
    user: "admin"
    password: "{{ ansible_password }}"
    body_format: json
    force_basic_auth: yes
  register: credentials_insert
  tags:
  - credential
  - add_stuff

- set_fact:
    new_machine_credential_id: "{{ credentials_insert.json.results[0].id }}"
  tags:
  - credential
  - add_stuff

