---
- name: Import the inventory
  shell: cd ~/networking-workshop/lab_inventory/ ; sudo awx-manage inventory_import --source=hosts --inventory-name="Workshop Inventory"
  tags:
  - inventory
  - add_stuff

- name: Get the ID of the new inventory
  uri:
    url: https://localhost/api/v2/inventory_scripts/?name=Workshop%20Inventory
    validate_certs: no
    method: GET
    user: admin
    password: "{{ ansible_ssh_pass }}"
    body_format: json
    force_basic_auth: yes
  register: inventory_script_insert
  tags:
  - inventory
  - add_stuff

