---
- name: Insert the new inventory
  uri:
    url: https://localhost/api/v2/inventories/
    validate_certs: no
    method: POST
    user: admin
    password: "{{ ansible_password }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |
      {
          "name": "Workshop Inventory",
          "description": "These are the instances populated automatically for you.",
          "organization": "1",
          "kind": "",
          "host_filter": null,
          "variables": "---\nansible_password: {{ ansible_password }}\nother_var: GoKEV",
          "insights_credential": null
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False
  tags:
  - inventory
  - add_stuff

- name: Import the inventory from text file
  shell: cd ~/networking-workshop/lab_inventory/ ; sudo awx-manage inventory_import --source=hosts --inventory-name="Workshop Inventory"
  tags:
  - inventory
  - add_stuff

- name: Get the ID of the new inventory
  uri:
    url: https://localhost/api/v2/inventories/?name=Workshop%20Inventory
    validate_certs: no
    method: GET
    user: admin
    password: "{{ ansible_ssh_pass }}"
    body_format: json
    force_basic_auth: yes
  register: inventory_insert
  tags:
  - inventory
  - add_stuff

- set_fact:
    new_inventory_id: "{{ inventory_insert.json.results[0].id }}"
  tags:
  - inventory
  - add_stuff

