---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  serial: 1

  tasks:
  - name: Use a single pattern that contains a comma formatted as a list
    raw: ls -1 ./varfiles/app_*yml
    register: filenames

  - name: debug filenames
    debug:
      msg: "filenames are {{ filenames }}"

  - name: loop one filename
    include: include-bigip-deploy-app.yml my_vip_varsfile="{{ item }}"
    with_items: "{{ filenames.stdout_lines }}"

  - name: SAVE RUNNING CONFIGURATION
    bigip_config:
      provider: "{{provider}}"
      save: true

  - name: "Now check your F5 at {{ hostvars['f5']['ansible_facts']['ansible_host'] }}"
  - debug:
      msg: "Log in to https://{{ hostvars['f5']['ansible_facts']['ansible_host'] }}:8443"

