- name: Variable examples
  hosts: localhost
  gather_facts: false

  vars:
    my_message: This is the default message set in the playbook.
    my_name: Default Name
    my_email: default@email.address

  tasks:
  - name: printing my_name
    debug:
      msg: "Hi.  My name is {{ my_name }}"

  - name: printing my_email
    debug:
      msg: "and my email is {{ my_email }}."

  - name: The dramatic sentence leading up to my message
    debug:
      msg: "If I could say one thing to the world, it would be: "


  - name: print out my_message as a variable
    debug:
      var: my_message
