---
wpdbname: "WordPress"
wpdbuser: "wordpressuser"
wpdbpass: "wordpresspass"
wpadmpass: "Password123"
wpadmfirst: "Adminstopher"
wpadmlast: "McAdminson"
wpadmemail: "amcadminson@fakedomain.tld"
wpwebpath: "/var/www/wordpress-root"

