---
- name: EPEL
  yum:
    name: epel-release
    state: present
  become: true

- name: PIP
  yum:
    name:
      - python2-pip
      - nano
    state: present
  become: true

- name: install nano
  yum:
    name: nano
    state: latest

- name: nanorc template
  template:
    src: templates/nanorc
    dest: /etc/nanorc
    owner: root
    group: wheel
    mode: 0644
    backup: yes
  become: yes

- name: copy json nanorc template
  copy:
    src: templates/json.nanorc
    dest: /usr/share/nano/json.nanorc
    owner: root
    group: wheel
    mode: 0644
  become: yes

- name: copy yaml nanorc template
  copy:
    src: templates/yaml.nanorc
    dest: /usr/share/nano/yaml.nanorc
    owner: root
    group: wheel
    mode: 0644
  become: yes

- pip:
    name: ansible-tower-cli
  become: yes
