---
- name: EPEL
  yum:
    name: epel-release
    state: present
  become: true

- name: PIP
  yum:
    name:
      - python2-pip
      - nano
    state: present
  become: true

- name: nanorc template
  template:
    src: templates/nanorc
    dest: /etc/nanorc
    owner: root
    group: root
    mode: 0644
  become: true

- pip:
    name: ansible-tower-cli
  become: true
