---
- name: Reset to before wordpress was installed
  hosts: all

  vars:
    - main_purpose: reset
    - webhostname: "{{ hostvars['lampweb']['ansible_nodename'] }}"
    - dbhostname: "{{ hostvars['lampdb']['ansible_facts']['eth0']['ipv4']['address'] }}"

  roles:
    - role: wordpress-server
