---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  serial: 1

  tasks:

    - name: "Parse the servernames on whitespace from the input string {{ server_names }}"
      set_fact:
        split_server_names: "{{ server_names.split() }}"

    - name: NODES
      bigip_node:
        host: "{{ item.ip }}"
        name: "{{ item.hostname }}"
      loop: "{{ f5_nodes }}"
      delegate_to: localhost
#      loop_control:
#        loop_var: loop_create_nodes
#      when: app_exists == 'True'

    - name: POOLS
      bigip_pool:
        name: "{{ item.poolname }}"
        lb_method: "{{ item.lb_method }}"
        monitors: "{{ item.monitors }}"
        monitor_type: "{{ item.monitor_type }}"
      loop: "{{ f5_pools }}"
#      when: app_exists == 'True'

    - name: POOL MEMBERS
      bigip_pool_member:
        state: "present"
        host: "{{ item.ip }}"
        name: "{{ item.hostname }}"
        host: "{{ item.port }}"
        name: "{{ item.poolname }}"
      loop: "{{ f5_nodes }}"
#      loop_control:
#        loop_var: loop_pool_members

    - name: VIP
      bigip_virtual_server:
        name: "{{ item.vipname }}"
        destination: "{{ item.priv_ip }}"
        port: "{{ item.port }}"
        enabled_vlans: "{{ item.vlans }}"
        all_profiles: ['http', 'clientssl', 'oneconnect']
        pool: "{{ item.pool }}"
        snat: "Automap"
      loop: "{{ f5_vips }}"

