---
- name: Insert the Lab Vault credential
  uri:
    url: https://localhost/api/v2/credentials/
    validate_certs: no
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |
      {
          "name": "Lab Vault",
          "description": "this is a vault credential",
          "organization": 1,
          "credential_type": 3,
          "inputs": {
              "vault_password": "redhat"
          }
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False

- name: Get the new credential ID
  uri:
    url: https://localhost/api/v2/credentials/?name=Lab%20Vault
    validate_certs: no
    method: GET
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
  register: vault_insert

- set_fact:
    new_vault_credential_id: "{{ vault_insert.json.results[0].id }}"

