---
- name: Insert the root machine credential
  uri:
    url: https://localhost/api/v2/credentials/
    validate_certs: no
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |
      {
          "name": "root user",
          "description": "Lab Machines Root User",
          "organization": 1,
          "credential_type": 1,
          "inputs": {
              "username": "root",
              "password": "redhat"
          }
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False

- name: Get the new credential ID
  uri:
    url: https://localhost/api/v2/credentials/?name=root%20user
    validate_certs: no
    method: GET
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
  register: credentials_insert

- set_fact:
    new_machine_credential_id: "{{ credentials_insert.json.results[0].id }}"

