---
#- name: Add tower hosts
#  tower_host:
#    name: localhost
#    description: "Local Host Group"
#    inventory: "Workshop Inventory"
#    state: present
#    tower_config_file: "~/networking-workshop/lab_inventory/hosts"
#
- name: Import the inventory
  shell: cd ~/networking-workshop/lab_inventory/ ; sudo awx-manage inventory_import --source=hosts --inventory-name="Workshop Inventory"

- name: Get the ID of the new inventory
  uri:
    url: https://localhost/api/v2/inventory_scripts/?name=Workshop%20Inventory
    validate_certs: no
    method: GET
    user: admin
    password: "{{ ansible_ssh_pass }}"
    body_format: json
    force_basic_auth: yes
  register: inventory_script_insert


