- name: Insert the LimeLight_Labs project
  uri:
    url: https://localhost/api/v2/projects/
    validate_certs: no
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
    status_code: 201
    body: |


      {
          "name": "F5 Lab Demo",
          "description": "",
          "local_path": "_11__f5_lab_demo",
          "scm_type": "git",
          "scm_url": "https://github.com/GoKEV/F5-workshop.git",
          "scm_branch": "",
          "scm_refspec": "",
          "scm_clean": true,
          "scm_delete_on_update": true,
          "credential": null,
          "timeout": 0,
          "organization": 1,
          "scm_update_on_launch": true,
          "scm_update_cache_timeout": 0,
          "allow_override": false,
          "custom_virtualenv": null
      }
  ignore_errors: yes
  no_log: True
  failed_when: False
  changed_when: False

## If the project already existed, the output is different from the input. Instead we query again and parse the ID here.
- name: Get ID from RedHatROoT-Ansible-Demos project ID
  uri:
    url: https://localhost/api/v2/projects/?name=F5%20Lab%20Demo
    validate_certs: no
    method: GET
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    body_format: json
    force_basic_auth: yes
  register: project_insert

- set_fact:
    new_project_id: "{{ project_insert.json.results[0].id }}"

